version: '3.3'

networks:
  news_net:
    external: true

services:

  db:
    image: postgres:11
    container_name: db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - news_net

  liquibase-pg:
    build:
      context: ./db-migrations/postgresql
    command: update
    restart: on-failure
    container_name: liquibase-pg
    environment:
      - LIQUIBASE_CHANGELOG=changelog.xml
      - LIQUIBASE_URL=jdbc:postgresql://db:5432/postgres
      - LIQUIBASE_USERNAME=user
      - LIQUIBASE_PASSWORD=pass
      - LIQUIBASE_OPTS=--defaultSchemaName=public --liquibaseSchemaName=public
    depends_on:
      - db
    networks:
      - news_net